---
kind: pipeline
type: docker
name: development

clone:
  disable: true

steps:
  - name: clone
    image: docker.io/bdebyl/alpine-git
    commands:
      - git clone https://github.com/debyltech/go-snipcart-api.git .
      - git checkout $DRONE_COMMIT

  - name: build
    image: docker.io/golang:1.20.3
    commands:
      - CGO_ENABLED=0 go build -tags netgo 

  - name: deploy-dev
    image: docker.io/bdebyl/awscli
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    commands:
      - apk add zip
      - zip go-snipcart-api.zip go-snipcart-api
      - aws lambda update-function-code --function-name go-snipcart-api --zip-file "fileb://go-snipcart-api.zip"
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
trigger:
  branch:
    - master
  event:
    include:
      - push
    exclude:
      - tag

---
kind: pipeline
type: docker
name: production

clone:
  disable: true

steps:
  - name: clone
    image: docker.io/bdebyl/alpine-git
    commands:
      - git clone https://github.com/debyltech/go-snipcart-api.git .
      - git checkout $DRONE_COMMIT

  - name: build
    image: docker.io/golang:1.20.3
    commands:
      - CGO_ENABLED=0 go build -tags netgo -ldflags "-X main.BuildVersion=$DRONE_TAG"

  - name: deploy-prod
    image: docker.io/bdebyl/awscli
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    commands:
      - apk add zip
      - zip go-snipcart-api.zip go-snipcart-api
      - aws lambda update-function-code --function-name webhooks-prod --zip-file "fileb://go-snipcart-api.zip"
trigger:
  branch:
    - master
  event:
    include:
      - tag
    exclude:
      - push
 
---
kind: signature
hmac: 754fa7c44c8d95a6d3c3ea5e4a9e5dc128b3cd8ea0ab8f9561a3baa2cd35c8c5

...
