---
kind: pipeline
type: docker
name: development

clone:
  disable: true

steps:
  - name: clone
    image: docker.io/bdebyl/alpine-git
    commands:
      - git clone https://github.com/debyltech/go-snipcart-api.git .
      - git checkout $DRONE_COMMIT

  - name: build
    image: docker.io/golang:1.20.3
    commands:
      - CGO_ENABLED=0 go build -tags netgo 

  - name: deploy-dev
    image: docker.io/bdebyl/awscli
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    commands:
      - apk add zip
      - zip go-snipcart-api.zip go-snipcart-api
      - aws lambda update-function-code --function-name snipcart-api-dev --zip-file "fileb://go-snipcart-api.zip"
    when:
      branch:
        - main
      event:
        exclude:
          - pull_request
trigger:
  branch:
    - main
  event:
    include:
      - push
    exclude:
      - tag

---
kind: pipeline
type: docker
name: production

clone:
  disable: true

steps:
  - name: clone
    image: docker.io/bdebyl/alpine-git
    commands:
      - git clone https://github.com/debyltech/go-snipcart-api.git .
      - git checkout $DRONE_COMMIT

  - name: build
    image: docker.io/golang:1.20.3
    commands:
      - CGO_ENABLED=0 go build -tags netgo -ldflags "-X main.BuildVersion=$DRONE_TAG"

  - name: deploy-prod
    image: docker.io/bdebyl/awscli
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    commands:
      - apk add zip
      - zip go-snipcart-api.zip go-snipcart-api
      - aws lambda update-function-code --function-name snipcart-api-prod --zip-file "fileb://go-snipcart-api.zip"
trigger:
  branch:
    - main
  event:
    include:
      - tag
    exclude:
      - push
 
---
kind: signature
hmac: 5ab2e77249b6c5b3c2ed98f21ffea3b315dd3358ec01bf4ac4f8e93b9c08936a

...
